export const FETCHING_COINS = 'FETCHING_COINS';
export const FETCHING_COINS_SUCCESS = 'FETCHING_COINS_SUCCESS';
export const FETCHING_COINS_FAIL = 'FETCHING_COINS_FAIL';

export const FETCHING_COIN = 'FETCHING_COIN';
export const FETCHING_COIN_SUCCESS = 'FETCHING_COIN_SUCCESS';
export const FETCHING_COIN_FAIL = 'FETCHING_COIN_FAIL';

export const TOGGLE_MENU = 'TOGGLE_MENU';
